[env]
platform = espressif32
board = esp32-p4-evboard
framework = espidf
monitor_speed = 115200
upload_speed = 460800
board_build.flash_mode = dio
board_build.flash_size = 16MB
board_build.psram_type = hex
board_build.partitions = partitions.csv
build_type = debug
extra_scripts = pre:extra_script.py
build_flags =
    -D CONFIG_IDF_EXPERIMENTAL_FEATURES=1
    -DLV_CONF_SKIP=1
lib_deps =
    lvgl/lvgl@9.5.0

[env:jc8012_10_display_lvgl_asset_framebuffer_smoke_r0]
build_flags = ${env.build_flags} -D BRICK_PANEL_ROTATION=0

[env:jc8012_10_display_lvgl_asset_framebuffer_smoke_r90]
build_flags = ${env.build_flags} -D BRICK_PANEL_ROTATION=90

[env:jc8012_10_display_lvgl_asset_framebuffer_smoke_r180]
build_flags = ${env.build_flags} -D BRICK_PANEL_ROTATION=180

[env:jc8012_10_display_lvgl_asset_framebuffer_smoke_r270]
build_flags = ${env.build_flags} -D BRICK_PANEL_ROTATION=270

[env:jc8012_10_display_lvgl_asset_framebuffer_smoke_color_r0]
build_flags = ${env.build_flags} -D BRICK_PANEL_ROTATION=0 -D BRICK_COLOR_ONLY=1

[env:jc8012_10_display_lvgl_asset_framebuffer_smoke_image_r0]
build_flags = ${env.build_flags} -D BRICK_PANEL_ROTATION=0 -D BRICK_IMAGE_ONLY=1

[env:jc8012_10_display_lvgl_asset_framebuffer_smoke_stream_r0]
build_flags = ${env.build_flags} -D BRICK_PANEL_ROTATION=0 -D BRICK_IMAGE_ONLY=1 -D BRICK_STREAM_TEST=1

[env:jc8012_10_display_lvgl_asset_framebuffer_smoke_touch_r0]
build_flags = ${env.build_flags} -D BRICK_PANEL_ROTATION=0 -D BRICK_LVGL_TOUCH=1 -D CONFIG_ESP_LCD_TOUCH_MAX_POINTS=5 -D CONFIG_ESP_LCD_TOUCH_MAX_BUTTONS=1

[env:jc8012_10_display_lvgl_asset_framebuffer_smoke_touch_r90]
build_flags = ${env.build_flags} -D BRICK_PANEL_ROTATION=90 -D BRICK_LVGL_TOUCH=1 -D CONFIG_ESP_LCD_TOUCH_MAX_POINTS=5 -D CONFIG_ESP_LCD_TOUCH_MAX_BUTTONS=1

[env:jc8012_10_display_lvgl_asset_framebuffer_smoke_touch_r180]
build_flags = ${env.build_flags} -D BRICK_PANEL_ROTATION=180 -D BRICK_LVGL_TOUCH=1 -D CONFIG_ESP_LCD_TOUCH_MAX_POINTS=5 -D CONFIG_ESP_LCD_TOUCH_MAX_BUTTONS=1

[env:jc8012_10_display_lvgl_asset_framebuffer_smoke_touch_r270]
build_flags = ${env.build_flags} -D BRICK_PANEL_ROTATION=270 -D BRICK_LVGL_TOUCH=1 -D CONFIG_ESP_LCD_TOUCH_MAX_POINTS=5 -D CONFIG_ESP_LCD_TOUCH_MAX_BUTTONS=1

[env:jc8012_10_display_lvgl_asset_framebuffer_smoke_fps_color_r0]
build_flags = ${env.build_flags} -D BRICK_PANEL_ROTATION=0 -D BRICK_FPS_TEST=1 -D BRICK_COLOR_ONLY=1

[env:jc8012_10_display_lvgl_asset_framebuffer_smoke_fps_asset_r0]
build_flags = ${env.build_flags} -D BRICK_PANEL_ROTATION=0 -D BRICK_FPS_TEST=1 -D BRICK_IMAGE_ONLY=1
