[platformio]
default_envs = termotechnika_st9727_display_touch_smoke

[env:termotechnika_st9727_display_touch_smoke]
platform = ststm32@19.7.1
board = termotechnika_st9727
framework = stm32cube
upload_protocol = stlink
monitor_speed = 115200
build_type = debug
extra_scripts = pre:extra_script.py
