[env:jc1060_7_display_touch_smoke]
platform = espressif32
board = esp32-p4-evboard
framework = espidf
monitor_speed = 115200
upload_speed = 460800
build_type = debug
extra_scripts = pre:extra_script.py
build_flags =
    -D CONFIG_IDF_EXPERIMENTAL_FEATURES=1
