[env:jc1060_7_display_touch_smoke]
platform = espressif32
board = esp32-p4-evboard
framework = espidf
monitor_speed = 115200
upload_speed = 460800
build_type = debug
build_flags =
    -I ${PROJECT_DIR}/../../../../libs/brick/libs/interfaces/include
    -I ${PROJECT_DIR}/../../../../libs/brick/libs/core/include
    -I ${PROJECT_DIR}/../../../../libs/brick/platforms/esp32/include
    -D CONFIG_IDF_EXPERIMENTAL_FEATURES=1
