[env:esp32s3_480_sd_card_filesystem_touch_smoke]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
upload_speed = 460800
board_build.flash_mode = dio
board_upload.flash_size = 16MB
build_type = debug
build_flags = -Iinclude -include board_config.h
extra_scripts = pre:extra_script.py
