[env]
platform = espressif32
board = esp32-p4-evboard
framework = espidf
monitor_speed = 115200
upload_speed = 460800
board_build.flash_mode = dio
board_build.flash_size = 16MB
board_build.psram_type = hex
build_type = debug
extra_scripts = pre:extra_script.py
build_flags = -D CONFIG_IDF_EXPERIMENTAL_FEATURES=1 -Iinclude -include board_config.h

[env:jc8012_10_display_touch_smoke_r0]
build_flags = ${env.build_flags} -D BRICK_PANEL_ROTATION=0

[env:jc8012_10_display_touch_smoke_r90]
build_flags = ${env.build_flags} -D BRICK_PANEL_ROTATION=90

[env:jc8012_10_display_touch_smoke_r180]
build_flags = ${env.build_flags} -D BRICK_PANEL_ROTATION=180

[env:jc8012_10_display_touch_smoke_r270]
build_flags = ${env.build_flags} -D BRICK_PANEL_ROTATION=270
