[platformio]
default_envs = esp12f_st7789_asset_stream_smoke

[env:esp12f_st7789_asset_stream_smoke]
platform = espressif8266
board = esp12e
framework = arduino
monitor_port = COM11
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
upload_port = COM11
upload_speed = 921600
board_build.flash_mode = dout
board_build.f_cpu = 160000000L
lib_deps =
  bodmer/TFT_eSPI@^2.5.43
build_flags =
  -DUSER_SETUP_LOADED=1
  -DST7789_DRIVER=1
  -DTFT_WIDTH=240
  -DTFT_HEIGHT=240
  -DTFT_MOSI=13
  -DTFT_SCLK=14
  -DTFT_CS=-1
  -DTFT_DC=0
  -DTFT_RST=2
  -DTFT_BL=5
  -DTFT_RGB_ORDER=TFT_BGR
  -DTOUCH_CS=-1
  -DTFT_BACKLIGHT_ON=LOW
  -DLOAD_GLCD=1
  -DSPI_FREQUENCY=40000000
  -DSPI_READ_FREQUENCY=10000000
  -DARDUINO_ESP8266_RELEASE_2_7_4_OR_NEWER=1
  -I$PROJECT_DIR/../../../libs/brick/libs/interfaces/include
  -I$PROJECT_DIR/../../../libs/brick/libs/core/include
  -I$PROJECT_DIR/../../../libs/brick/platforms/esp8266/include
